#!/usr/bin/env bash

case "$1" in
shutdown)
    systemctl poweroff
    ;;
reboot | restart)
    systemctl reboot
    ;;
suspend)
    lock_screen
    sleep 1
    systemctl suspend
    ;;
hibernate)
    lock_screen
    systemctl hibernate
    ;;
logout)
    hyprctl dispatch exit
    ;;
lock)
    hyprlock
    ;;
*)
    echo $"Usage: $0 {shutdown|reboot|suspend|hibernate|logout|lock|close}"
    exit 1
    ;;
esac
